In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [3]:
df=pd.read_csv("HR.csv")
df = df.head(200)
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

In [5]:
from sklearn.preprocessing import LabelEncoder
dfle=df #dataframe for label encoding
dfle.salary= LabelEncoder().fit_transform(dfle.salary)
dfle

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,1
1,0.80,0.86,5,262,6,0,1,0,sales,2
2,0.11,0.88,7,272,4,0,1,0,sales,2
3,0.72,0.87,5,223,5,0,1,0,sales,1
4,0.37,0.52,2,159,3,0,1,0,sales,1
...,...,...,...,...,...,...,...,...,...,...
195,0.09,0.80,6,304,4,0,1,0,technical,1
196,0.27,0.54,7,278,3,0,1,0,technical,1
197,0.10,0.91,6,287,4,0,1,0,technical,1
198,0.10,0.89,7,285,4,0,1,0,technical,1
199,0.77,0.94,5,226,6,0,1,0,support,1

In [12]:
from sklearn.preprocessing import LabelEncoder
dfle=df #dataframe for label encoding
dfle.Department= LabelEncoder().fit_transform(dfle.Department)
dfle

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,6,1
1,0.80,0.86,5,262,6,0,1,0,6,2
2,0.11,0.88,7,272,4,0,1,0,6,2
3,0.72,0.87,5,223,5,0,1,0,6,1
4,0.37,0.52,2,159,3,0,1,0,6,1
...,...,...,...,...,...,...,...,...,...,...
195,0.09,0.80,6,304,4,0,1,0,8,1
196,0.27,0.54,7,278,3,0,1,0,8,1
197,0.10,0.91,6,287,4,0,1,0,8,1
198,0.10,0.89,7,285,4,0,1,0,8,1
199,0.77,0.94,5,226,6,0,1,0,7,1

In [13]:
x= dfle[['salary','Department','satisfaction_level']].values
x

array([[1.  , 6.  , 0.38],
       [2.  , 6.  , 0.8 ],
       [2.  , 6.  , 0.11],
       [1.  , 6.  , 0.72],
       [1.  , 6.  , 0.37],
       [1.  , 6.  , 0.41],
       [1.  , 6.  , 0.1 ],
       [1.  , 6.  , 0.92],
       [1.  , 6.  , 0.89],
       [1.  , 6.  , 0.42],
       [1.  , 6.  , 0.45],
       [1.  , 6.  , 0.11],
       [1.  , 6.  , 0.84],
       [1.  , 6.  , 0.41],
       [1.  , 6.  , 0.36],
       [1.  , 6.  , 0.38],
       [1.  , 6.  , 0.45],
       [1.  , 6.  , 0.78],
       [1.  , 6.  , 0.45],
       [1.  , 6.  , 0.76],
       [1.  , 6.  , 0.11],
       [1.  , 6.  , 0.38],
       [1.  , 6.  , 0.09],
       [1.  , 6.  , 0.46],
       [1.  , 6.  , 0.4 ],
       [1.  , 6.  , 0.89],
       [1.  , 6.  , 0.82],
       [1.  , 6.  , 0.4 ],
       [1.  , 1.  , 0.41],
       [1.  , 1.  , 0.38],
       [1.  , 1.  , 0.09],
       [1.  , 2.  , 0.45],
       [1.  , 2.  , 0.4 ],
       [1.  , 2.  , 0.45],
       [1.  , 2.  , 0.84],
       [1.  , 8.  , 0.1 ],
       [1.  , 8.  , 0.38],
       [1.  , 8.  , 0.45],
       [1.  , 8.  , 0.11],
       [1.  , 8.  , 0.41],
       [1.  , 8.  , 0.87],
       [1.  , 8.  , 0.45],
       [1.  , 8.  , 0.4 ],
       [1.  , 8.  , 0.1 ],
       [1.  , 8.  , 0.09],
       [1.  , 8.  , 0.84],
       [1.  , 7.  , 0.4 ],
       [1.  , 7.  , 0.57],
       [1.  , 7.  , 0.4 ],
       [1.  , 7.  , 0.43],
       [1.  , 7.  , 0.13],
       [1.  , 7.  , 0.44],
       [1.  , 7.  , 0.38],
       [1.  , 7.  , 0.39],
       [1.  , 7.  , 0.1 ],
       [1.  , 7.  , 0.37],
       [1.  , 7.  , 0.11],
       [1.  , 8.  , 0.1 ],
       [1.  , 8.  , 0.38],
       [1.  , 8.  , 0.85],
       [2.  , 3.  , 0.85],
       [2.  , 0.  , 0.11],
       [2.  , 0.  , 0.1 ],
       [2.  , 0.  , 0.36],
       [2.  , 0.  , 0.11],
       [2.  , 0.  , 0.81],
       [2.  , 5.  , 0.43],
       [2.  , 5.  , 0.9 ],
       [2.  , 5.  , 0.76],
       [2.  , 5.  , 0.43],
       [2.  , 0.  , 0.74],
       [2.  , 5.  , 0.09],
       [0.  , 5.  , 0.45],
       [1.  , 5.  , 0.09],
       [2.  , 5.  , 0.11],
       [2.  , 5.  , 0.11],
       [2.  , 5.  , 0.1 ],
       [2.  , 4.  , 0.4 ],
       [1.  , 6.  , 0.43],
       [1.  , 1.  , 0.39],
       [1.  , 7.  , 0.45],
       [1.  , 8.  , 0.38],
       [1.  , 3.  , 0.79],
       [1.  , 4.  , 0.84],
       [1.  , 4.  , 0.11],
       [1.  , 4.  , 0.11],
       [1.  , 6.  , 0.17],
       [1.  , 6.  , 0.44],
       [1.  , 6.  , 0.37],
       [1.  , 6.  , 0.1 ],
       [1.  , 6.  , 0.4 ],
       [1.  , 6.  , 0.89],
       [1.  , 6.  , 0.42],
       [1.  , 6.  , 0.46],
       [1.  , 6.  , 0.09],
       [1.  , 6.  , 0.37],
       [1.  , 6.  , 0.1 ],
       [1.  , 6.  , 0.1 ],
       [1.  , 6.  , 0.11],
       [2.  , 6.  , 0.9 ],
       [2.  , 6.  , 0.38],
       [2.  , 6.  , 0.36],
       [2.  , 6.  , 0.42],
       [2.  , 6.  , 0.09],
       [2.  , 6.  , 0.43],
       [2.  , 1.  , 0.24],
       [2.  , 1.  , 0.91],
       [2.  , 1.  , 0.44],
       [2.  , 2.  , 0.71],
       [2.  , 2.  , 0.4 ],
       [2.  , 2.  , 0.43],
       [0.  , 2.  , 0.09],
       [1.  , 8.  , 0.43],
       [2.  , 8.  , 0.9 ],
       [2.  , 8.  , 0.84],
       [2.  , 8.  , 0.37],
       [2.  , 8.  , 0.86],
       [1.  , 8.  , 0.11],
       [1.  , 8.  , 0.37],
       [1.  , 8.  , 0.4 ],
       [1.  , 8.  , 0.14],
       [1.  , 8.  , 0.4 ],
       [1.  , 8.  , 0.75],
       [1.  , 7.  , 0.11],
       [1.  , 7.  , 0.46],
       [1.  , 7.  , 0.11],
       [1.  , 7.  , 0.38],
       [1.  , 7.  , 0.7 ],
       [1.  , 7.  , 0.09],
       [1.  , 7.  , 0.37],
       [1.  , 7.  , 0.1 ],
       [1.  , 7.  , 0.38],
       [1.  , 7.  , 0.9 ],
       [1.  , 7.  , 0.44],
       [1.  , 8.  , 0.36],
       [1.  , 8.  , 0.31],
       [1.  , 8.  , 0.1 ],
       [1.  , 3.  , 0.42],
       [1.  , 0.  , 0.74],
       [1.  , 0.  , 0.73],
       [1.  , 0.  , 0.09],
       [1.  , 0.  , 0.45],
       [1.  , 0.  , 0.11],
       [1.  , 5.  , 0.37],
       [1.  , 5.  , 0.84],
       [1.  , 5.  , 0.41],
       [1.  , 5.  , 0.76],
       [1.  , 0.  , 0.11],
       [1.  , 4.  , 0.84],
       [1.  , 4.  , 0.39],
       [1.  , 4.  , 0.11],
       [1.  , 4.  , 0.45],
       [1.  , 4.  , 0.37],
       [1.  , 4.  , 0.4 ],
       [1.  , 6.  , 0.39],
       [1.  , 1.  , 0.11],
       [1.  , 7.  , 0.83],
       [1.  , 8.  , 0.11],
       [1.  , 3.  , 0.39],
       [1.  , 4.  , 0.45],
       [1.  , 4.  , 0.1 ],
       [1.  , 4.  , 0.9 ],
       [1.  , 6.  , 0.45],
       [1.  , 6.  , 0.79],
       [1.  , 6.  , 0.9 ],
       [1.  , 6.  , 0.11],
       [1.  , 6.  , 0.43],
       [1.  , 6.  , 0.31],
       [1.  , 6.  , 0.32],
       [1.  , 6.  , 0.45],
       [1.  , 6.  , 0.81],
       [1.  , 6.  , 0.41],
       [1.  , 6.  , 0.11],
       [1.  , 6.  , 0.1 ],
       [1.  , 6.  , 0.7 ],
       [1.  , 6.  , 0.54],
       [1.  , 6.  , 0.41],
       [2.  , 6.  , 0.38],
       [2.  , 6.  , 0.37],
       [2.  , 6.  , 0.11],
       [2.  , 6.  , 0.4 ],
       [2.  , 1.  , 0.1 ],
       [2.  , 1.  , 0.89],
       [2.  , 1.  , 0.11],
       [2.  , 2.  , 0.36],
       [2.  , 2.  , 0.4 ],
       [2.  , 2.  , 0.09],
       [2.  , 2.  , 0.4 ],
       [2.  , 8.  , 0.37],
       [0.  , 8.  , 0.44],
       [1.  , 8.  , 0.09],
       [2.  , 8.  , 0.92],
       [2.  , 8.  , 0.74],
       [2.  , 8.  , 0.09],
       [2.  , 8.  , 0.89],
       [1.  , 8.  , 0.09],
       [1.  , 8.  , 0.27],
       [1.  , 8.  , 0.1 ],
       [1.  , 8.  , 0.1 ],
       [1.  , 7.  , 0.77]])

In [14]:
y = dfle.left.values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [37]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('salary',OneHotEncoder(),[0])],remainder ='passthrough')
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('salary', OneHotEncoder(), [0])])

In [39]:
x= ct.fit_transform(x)
x

IndexError: tuple index out of range

In [17]:
reg=linear_model.LinearRegression()
reg

LinearRegression()

In [18]:
reg.fit(x,y)

LinearRegression()

In [19]:
reg.predict(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
reg.predict([[0,0,1,60,38]])

array([1.])

In [22]:
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,6,1
1,0.80,0.86,5,262,6,0,1,0,6,2
2,0.11,0.88,7,272,4,0,1,0,6,2
3,0.72,0.87,5,223,5,0,1,0,6,1
4,0.37,0.52,2,159,3,0,1,0,6,1
...,...,...,...,...,...,...,...,...,...,...
195,0.09,0.80,6,304,4,0,1,0,8,1
196,0.27,0.54,7,278,3,0,1,0,8,1
197,0.10,0.91,6,287,4,0,1,0,8,1
198,0.10,0.89,7,285,4,0,1,0,8,1
199,0.77,0.94,5,226,6,0,1,0,7,1

In [25]:
#cols = OneHotEncoder().get_feature_names_out(["salary"])

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [26]:
from sklearn.compose import ColumnTransformer

In [27]:
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,6,1
1,0.80,0.86,5,262,6,0,1,0,6,2
2,0.11,0.88,7,272,4,0,1,0,6,2
3,0.72,0.87,5,223,5,0,1,0,6,1
4,0.37,0.52,2,159,3,0,1,0,6,1
...,...,...,...,...,...,...,...,...,...,...
195,0.09,0.80,6,304,4,0,1,0,8,1
196,0.27,0.54,7,278,3,0,1,0,8,1
197,0.10,0.91,6,287,4,0,1,0,8,1
198,0.10,0.89,7,285,4,0,1,0,8,1
199,0.77,0.94,5,226,6,0,1,0,7,1

In [29]:
df['salary'].unique()

array([1, 2, 0])

In [32]:
ct = ColumnTransformer(transformers=[('salary',OneHotEncoder(),[0])],remainder ='passthrough')

In [33]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('salary', OneHotEncoder(), [0])])

In [40]:
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,6,1
1,0.80,0.86,5,262,6,0,1,0,6,2
2,0.11,0.88,7,272,4,0,1,0,6,2
3,0.72,0.87,5,223,5,0,1,0,6,1
4,0.37,0.52,2,159,3,0,1,0,6,1
...,...,...,...,...,...,...,...,...,...,...
195,0.09,0.80,6,304,4,0,1,0,8,1
196,0.27,0.54,7,278,3,0,1,0,8,1
197,0.10,0.91,6,287,4,0,1,0,8,1
198,0.10,0.89,7,285,4,0,1,0,8,1
199,0.77,0.94,5,226,6,0,1,0,7,1

In [42]:
x = dfle[['salary','Department','satisfaction_level']].values

In [43]:
x = ct.fit_transform(x)

In [46]:
X = x[:,1:]

In [53]:
df3=pd.DataFrame(X)

In [59]:
df3

       0    1    2     3
0    1.0  0.0  6.0  0.38
1    0.0  1.0  6.0  0.80
2    0.0  1.0  6.0  0.11
3    1.0  0.0  6.0  0.72
4    1.0  0.0  6.0  0.37
..   ...  ...  ...   ...
195  1.0  0.0  8.0  0.09
196  1.0  0.0  8.0  0.27
197  1.0  0.0  8.0  0.10
198  1.0  0.0  8.0  0.10
199  1.0  0.0  7.0  0.77

[200 rows x 4 columns]

In [60]:
df2

     salary  Department  satisfaction_level
0         1           6                0.38
1         2           6                0.80
2         2           6                0.11
3         1           6                0.72
4         1           6                0.37
..      ...         ...                 ...
195       1           8                0.09
196       1           8                0.27
197       1           8                0.10
198       1           8                0.10
199       1           7                0.77

[200 rows x 3 columns]

In [62]:
df2=df[['salary','Department','satisfaction_level']]

In [63]:
df2

     salary  Department  satisfaction_level
0         1           6                0.38
1         2           6                0.80
2         2           6                0.11
3         1           6                0.72
4         1           6                0.37
..      ...         ...                 ...
195       1           8                0.09
196       1           8                0.27
197       1           8                0.10
198       1           8                0.10
199       1           7                0.77

[200 rows x 3 columns]

In [64]:
df2=pd.concat(df3[[0,1,2]])

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"