In [4]:
!pip install plotly

Collecting plotly
  Downloading plotly-6.3.1-py3-none-any.whl.metadata (8.5 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.10.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from plotly) (25.0)
Downloading plotly-6.3.1-py3-none-any.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 263.7 kB/s eta 0:00:36
   -- ------------------------------------- 0.5/9.8 MB 263.7 kB/s eta 0:00:36
   -- ------------------------------------- 0.5/9.8 MB 263.7 kB/s eta 0:00:36
   -- ------------------------------------- 0.5/9.8 MB 263.7 kB/s eta 0:00:36
   --- ------------------------------------ 0.8/9.8 MB 279.0 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 279.0 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 279.0 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 279.0 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 279.0 kB/s eta 0:00:33
   ---- ----------------------------------- 1.0/9.8 MB 280.2 kB/s eta 0:00:32
   ---- ----------------------------------- 1.0/9.8 MB 280.2 kB/s eta 0:00:32
   ---- ----------------------------------- 1.0/9.8 MB 280.2 kB/s eta 0:00:32
   ---- ----------------------------------- 1.0/9.8 MB 280.2 kB/s eta 0:00:32
   ---- ----------------------------------- 1.0/9.8 MB 280.2 kB/s eta 0:00:32
   ----- ---------------------------------- 1.3/9.8 MB 265.5 kB/s eta 0:00:33
   ----- ---------------------------------- 1.3/9.8 MB 265.5 kB/s eta 0:00:33
   ----- ---------------------------------- 1.3/9.8 MB 265.5 kB/s eta 0:00:33
   ----- ---------------------------------- 1.3/9.8 MB 265.5 kB/s eta 0:00:33
   ----- ---------------------------------- 1.3/9.8 MB 265.5 kB/s eta 0:00:33
   ----- ---------------------------------- 1.3/9.8 MB 265.5 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------ --------------------------------- 1.6/9.8 MB 253.4 kB/s eta 0:00:33
   ------- -------------------------------- 1.8/9.8 MB 235.2 kB/s eta 0:00:35
   ------- -------------------------------- 1.8/9.8 MB 235.2 kB/s eta 0:00:35
   ------- -------------------------------- 1.8/9.8 MB 235.2 kB/s eta 0:00:35
   ------- -------------------------------- 1.8/9.8 MB 235.2 kB/s eta 0:00:35
   ------- -------------------------------- 1.8/9.8 MB 235.2 kB/s eta 0:00:35
   ------- -------------------------------- 1.8/9.8 MB 235.2 kB/s eta 0:00:35
   -------- ------------------------------- 2.1/9.8 MB 229.9 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 229.9 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 229.9 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 229.9 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 229.9 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 229.8 kB/s eta 0:00:33
   --------- ------------------------------ 2.4/9.8 MB 229.8 kB/s eta 0:00:33
   --------- ------------------------------ 2.4/9.8 MB 229.8 kB/s eta 0:00:33
   --------- ------------------------------ 2.4/9.8 MB 229.8 kB/s eta 0:00:33
   --------- ------------------------------ 2.4/9.8 MB 229.8 kB/s eta 0:00:33
   ---------- ----------------------------- 2.6/9.8 MB 229.8 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 229.8 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 229.8 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 229.8 kB/s eta 0:00:32
   ---------- ----------------------------- 2.6/9.8 MB 229.8 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 232.3 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.8 MB 232.3 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.8 MB 232.3 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.8 MB 232.3 kB/s eta 0:00:30
   ----------- ---------------------------- 2.9/9.8 MB 232.3 kB/s eta 0:00:30
   ------------ --------------------------- 3.1/9.8 MB 234.2 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.8 MB 234.2 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.8 MB 234.2 kB/s eta 0:00:29
   ------------ --------------------------- 3.1/9.8 MB 234.2 kB/s eta 0:00:29
   ------------- -------------------------- 3.4/9.8 MB 236.5 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 236.5 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 236.5 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 236.5 kB/s eta 0:00:28
   ------------- -------------------------- 3.4/9.8 MB 236.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   -------------- ------------------------- 3.7/9.8 MB 236.7 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   --------------- ------------------------ 3.9/9.8 MB 186.2 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14
   ----------------- ---------------------- 4.2/9.8 MB 18.0 kB/s eta 0:05:14

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pandas>=1.2 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\youexcel\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
import plotly.express as px
from word2number import w2n

In [8]:
df= pd.read_csv("homeprices-town.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [11]:
dumiesdf = pd.get_dummies(df.town)
dumiesdf

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [14]:
dumiesdf['monroe township']=dumiesdf['monroe township'].replace({False:0,True:1})
dumiesdf['monroe township']

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
Name: monroe township, dtype: int64

In [16]:
dumiesdf = dumiesdf.astype(int)
dumiesdf

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [17]:
merge =pd.concat([df,dumiesdf],axis='columns')
merge

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [18]:
final = merge.drop(['town','west windsor'],axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [19]:
y = final.price

In [20]:
x= final.drop('price',axis='columns')
x

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [21]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [22]:
model.fit(x,y)

LinearRegression()

In [23]:
model.predict(x)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [24]:
model.score(x,y)

0.9573929037221872

In [25]:
model.predict([[5000,1,0]])

C:\Users\YOUEXCEL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([844263.59922594])

In [26]:
model.predict([[5000,0,0]])

C:\Users\YOUEXCEL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([884277.57471508])

In [28]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [30]:
dfle =df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [33]:
x=dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [35]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [36]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town',OneHotEncoder(),[0])],remainder ='passthrough')

In [38]:
x = ct.fit_transform(x)
x

array([[0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [39]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('town', OneHotEncoder(), [0])])